#!/usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Vinelab\ClientGenerator\Commands\ClientCreatorCommand;
use Vinelab\ClientGenerator\Commands\ClientDeletorCommand;
use Vinelab\ClientGenerator\Commands\ClientGetterCommand;
use Vinelab\ClientGenerator\Commands\ClientListingCommand;
use Vinelab\ClientGenerator\Commands\ClientSecretRegenerationCommand;

$application = new Application();

# add our commands
$application->add(new ClientCreatorCommand());
$application->add(new ClientDeletorCommand());
$application->add(new ClientListingCommand());
$application->add(new ClientGetterCommand());
$application->add(new ClientSecretRegenerationCommand());

$application->run();
