#!/usr/bin/env php

<?php
/**
 * @author Charalampos Raftopoulos <harris@vinelab.com>
 */
if (version_compare(phpversion(), '5.4', '<')) {
    fwrite(STDERR, "PHP needs to be a minimum version of PHP 5.4\n");
    exit(1);
}
// installed via composer?
if (file_exists($a = __DIR__.'/../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__.'/vendor/autoload.php';
}

use Symfony\Component\Console\Application;
use Vinelab\ClientGenerator\Commands\ClientCreatorCommand;
use Vinelab\ClientGenerator\Commands\ClientGetterCommand;
use Vinelab\ClientGenerator\Commands\ClientListingCommand;
use Vinelab\ClientGenerator\Commands\ClientRemovalCommand;
use Vinelab\ClientGenerator\Commands\ClientSecretRegenerationCommand;

$application = new Application();

# add our commands
$application->add(new ClientCreatorCommand());
$application->add(new ClientRemovalCommand());
$application->add(new ClientListingCommand());
$application->add(new ClientGetterCommand());
$application->add(new ClientSecretRegenerationCommand());

$application->run();
